### ISSUE TITLE
[General] Option for saving Prospero session

### ISSUE THREAD

**Issue by jonnyishman** [jonathanlintott/Prospero#6]
From Trine.

**Comment by jonnyishman** [comment]
Saving sessions is very important and I agree that this needs to be in Prospero.

Unfortunately, it is also a lot of work to build session saving. The amount of work is probably comparable to building a whole new module. We'll see how we do with time constraints if this feature will be in the initial release or added afterwards.

**Comment by hklemm** [comment]
As difficult as serialising something like the Prospero stuff is, you should think about some rudimentary session saving for the first version. I just again saw a windows box going down because of maintenance. If you have a lot of surfaces etc. and have to reload everything every time windows does odd things, people will hate you.

**Comment by jonnyishman** [comment]
If we run out of time to include serialising before first release then I could build in a simple importer/exporter that dumps all the h5geo files into a specified folder. At least that then saves having to re-do the data importing which is usually the annoying time-consuming part.

**Comment by hklemm** [comment]
Well, you could also combine that approach with a .pkl file for the parameters and you are essentially there.

**Comment by jonnyishman** [comment]
Session saving has been implemented and seems to work aside from a few kinks which hopefully will make themselves obvious over the next couple of weeks.
